[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "geo"
version = "0.0.0"
description = "Минимальный проект для гео-работ"
authors = [ { name = "", email = "" } ]

[tool.pytest]
minversion = "6.0"
